### ISSUE TITLE
Crud api generator: Include caching in crud api

### ISSUE THREAD

**Issue by gurjotmindgrep** [godspeedsystems/gs-node-service#484]
- update the crud generator to include caching in read and invalidate in update/create/delete.
- First check whether caching is defined in config before generating crud
-  extend the Prisma, caching w/ TTL
- Use this parameter in workflow prisma task, i.e read task

**Comment by ashutoshmindgrep** [comment]
This issue is regarding asking a user if he want's to add caching while generating `gen-crud-api`.

@gnani1226: Please follow these steps.

1. Create a new project with PostgresDB and Redis.
2. Try out `com.gs.datastore` with redis. (find the documentation for `redis as datasource`)
3. Then go through the caching section of the documentation, understand it, and implement it.

Once done, Let's connect again.
