### ISSUE TITLE
Observability in v2

### ISSUE THREAD

**Issue by rohitgodspeed** [godspeedsystems/gs-node-service#749]
This master issue is linked to five issues listed below. We need to test and close this.
Also check #116 child of this issue
~~~~

To add logs, traces and metrics in v2 in a pluggable approach so that it can be optional. OTEL_ENABLED shall be used as a global flag to enable observability in Godspeed.
| Env Variable | Description |
| ------------ | ------------ | 
| OTEL_ENABLED | To enable/disable observability in Godspeed. Default value is false. |

**Comment by mastersilv3r** [comment]
It seems this issue is already done. @gurjotmindgrep please have a look at what is remaining and @sundar-godspeed can close it with your help. I see that otel command is already there in plugin. we just need to test and close this. Lets do that and save developer few steps to manually do. As well a repository will not uncessarily be used unless we enable via this command. so metrics, and tracing libraries should not be used unless otel enabled.

**Comment by mastersilv3r** [comment]
Leaving the child issues open and closing this
